#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Paired inference comparison on one shared inference dataset.

This script compares pure PyMatching with one or more predecoder models on the
same samples for each measurement basis. Samples are generated by Stim unless
``--stim-samples-dir`` points to external ``.dets`` artifacts. It is
intentionally separate from the Hydra workflow so the standard train/inference
entry points stay unchanged.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import os
import random
import sys
import time
from dataclasses import dataclass
from itertools import combinations
from pathlib import Path
from types import SimpleNamespace
from typing import Any

import numpy as np
import pymatching
import torch
from omegaconf import OmegaConf
from torch.utils.data import DataLoader

CODE_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = CODE_ROOT.parent
if str(CODE_ROOT) not in sys.path:
    sys.path.insert(0, str(CODE_ROOT))

from scripts.config_paths import config_path  # noqa: E402
from data.factory import DatapipeFactory  # noqa: E402
from evaluation.logical_error_rate import (  # noqa: E402
    PreDecoderMemoryEvalModule,
    _build_stab_maps,
)
from training.utils import dict_to_device  # noqa: E402
from workflows.config_validator import (  # noqa: E402
    apply_public_defaults_and_model,
    validate_public_config,
)
from model.checkpoint_loader import load_model_checkpoint  # noqa: E402


@dataclass(frozen=True)
class ModelSpec:
    name: str
    model_id: int
    checkpoint: Path


@dataclass(frozen=True)
class ComparisonSpec:
    candidate: str
    baseline: str


@dataclass(frozen=True)
class FactorialContrastSpec:
    name: str
    cell_11: str
    cell_10: str
    cell_01: str
    cell_00: str


@dataclass
class SyndromeDensityAccumulator:
    """Stream shot-level syndrome-density moments without storing every sample."""

    shots: int = 0
    syndrome_ones: int = 0
    syndrome_elements: int = 0
    shot_density_sum: float = 0.0
    shot_density_sum_squares: float = 0.0

    def update(self, syndromes: np.ndarray) -> None:
        values = np.asarray(syndromes, dtype=np.uint8)
        if values.ndim == 1:
            values = values.reshape(1, -1)
        if values.ndim != 2 or values.shape[1] == 0:
            raise ValueError(
                "syndromes must be a non-empty-width 2D array, "
                f"got shape={values.shape}"
            )
        ones_per_shot = np.count_nonzero(values, axis=1).astype(np.float64)
        densities = ones_per_shot / float(values.shape[1])
        self.shots += int(values.shape[0])
        self.syndrome_ones += int(ones_per_shot.sum())
        self.syndrome_elements += int(values.size)
        self.shot_density_sum += float(densities.sum())
        self.shot_density_sum_squares += float(np.square(densities).sum())

    def statistics(self, prefix: str) -> dict[str, float | int]:
        if not prefix:
            raise ValueError("density prefix must not be empty")
        center = (
            float(self.syndrome_ones / self.syndrome_elements)
            if self.syndrome_elements
            else float("nan")
        )
        if self.shots > 1:
            numerator = self.shot_density_sum_squares - (
                self.shot_density_sum * self.shot_density_sum / self.shots
            )
            variance = max(0.0, numerator / (self.shots - 1))
            standard_error = float(np.sqrt(variance / self.shots))
        else:
            standard_error = 0.0 if self.shots == 1 else float("nan")
        margin = 1.96 * standard_error
        return {
            f"{prefix}_density_shots": self.shots,
            f"{prefix}_syndrome_ones": self.syndrome_ones,
            f"{prefix}_syndrome_elements": self.syndrome_elements,
            f"{prefix}_density_shot_sum": self.shot_density_sum,
            f"{prefix}_density_shot_sum_squares": self.shot_density_sum_squares,
            f"{prefix}_syndrome_density": center,
            f"{prefix}_density_standard_error": standard_error,
            f"{prefix}_density_ci95_low": max(0.0, center - margin),
            f"{prefix}_density_ci95_high": min(1.0, center + margin),
        }


def combine_density_statistics(
    rows: list[dict[str, Any]],
    prefix: str,
) -> dict[str, float | int]:
    """Combine density sufficient statistics using detector-element weighting."""

    accumulator = SyndromeDensityAccumulator()
    for row in rows:
        accumulator.shots += int(row.get(f"{prefix}_density_shots", 0))
        accumulator.syndrome_ones += int(row.get(f"{prefix}_syndrome_ones", 0))
        accumulator.syndrome_elements += int(
            row.get(f"{prefix}_syndrome_elements", 0)
        )
        accumulator.shot_density_sum += float(
            row.get(f"{prefix}_density_shot_sum", 0.0)
        )
        accumulator.shot_density_sum_squares += float(
            row.get(f"{prefix}_density_shot_sum_squares", 0.0)
        )
    return accumulator.statistics(prefix)


def density_reduction_statistics(
    input_density: float,
    residual_density: float,
) -> dict[str, float]:
    input_value = float(input_density)
    residual_value = float(residual_density)
    delta = residual_value - input_value
    if input_value > 0 and math.isfinite(input_value):
        reduction_fraction = (input_value - residual_value) / input_value
    else:
        reduction_fraction = float("nan")
    if residual_value > 0 and math.isfinite(residual_value):
        reduction_factor = input_value / residual_value
    elif input_value > 0 and residual_value == 0:
        reduction_factor = float("inf")
    else:
        reduction_factor = float("nan")
    return {
        "density_delta": delta,
        "density_reduction_fraction": reduction_fraction,
        "density_reduction_factor": reduction_factor,
    }


def model_density_statistics(
    input_accumulator: SyndromeDensityAccumulator,
    residual_accumulator: SyndromeDensityAccumulator,
) -> dict[str, float | int]:
    input_stats = input_accumulator.statistics("input")
    residual_stats = residual_accumulator.statistics("residual")
    return {
        **input_stats,
        **residual_stats,
        **density_reduction_statistics(
            float(input_stats["input_syndrome_density"]),
            float(residual_stats["residual_syndrome_density"]),
        ),
    }


def parse_model_spec(value: str) -> ModelSpec:
    parts = value.split(":", 2)
    if len(parts) != 3:
        raise argparse.ArgumentTypeError(
            "--model must be formatted as name:model_id:/path/to/checkpoint"
        )
    name, model_id_raw, checkpoint_raw = parts
    if not name:
        raise argparse.ArgumentTypeError("model name must not be empty")
    try:
        model_id = int(model_id_raw)
    except ValueError as exc:
        raise argparse.ArgumentTypeError(f"invalid model_id: {model_id_raw}") from exc
    checkpoint = Path(checkpoint_raw).expanduser()
    if not checkpoint.is_absolute():
        checkpoint = REPO_ROOT / checkpoint
    return ModelSpec(name=name, model_id=model_id, checkpoint=checkpoint)


def parse_comparison_spec(value: str) -> ComparisonSpec:
    parts = value.split(":", 1)
    if len(parts) != 2 or not all(part.strip() for part in parts):
        raise argparse.ArgumentTypeError(
            "--paired-comparison must be formatted as candidate:baseline"
        )
    candidate, baseline = (part.strip() for part in parts)
    if candidate == baseline:
        raise argparse.ArgumentTypeError("candidate and baseline must be different methods")
    return ComparisonSpec(candidate=candidate, baseline=baseline)


def parse_factorial_contrast_spec(value: str) -> FactorialContrastSpec:
    parts = [part.strip() for part in value.split(":")]
    if len(parts) != 5 or not all(parts):
        raise argparse.ArgumentTypeError(
            "--factorial-contrast must be formatted as "
            "name:cell_11:cell_10:cell_01:cell_00"
        )
    name, cell_11, cell_10, cell_01, cell_00 = parts
    if len({cell_11, cell_10, cell_01, cell_00}) != 4:
        raise argparse.ArgumentTypeError("factorial contrast cells must be four distinct methods")
    return FactorialContrastSpec(name, cell_11, cell_10, cell_01, cell_00)


def factorial_contrast_statistics(
    cell_11_errors: np.ndarray,
    cell_10_errors: np.ndarray,
    cell_01_errors: np.ndarray,
    cell_00_errors: np.ndarray,
) -> dict[str, float | int]:
    masks = [
        np.asarray(errors, dtype=np.bool_).reshape(-1)
        for errors in (cell_11_errors, cell_10_errors, cell_01_errors, cell_00_errors)
    ]
    shapes = {mask.shape for mask in masks}
    if len(shapes) != 1:
        raise ValueError(f"factorial contrast masks must have one shape: {sorted(shapes)}")
    samples = int(masks[0].size)
    if samples == 0:
        raise ValueError("factorial contrast masks must not be empty")
    contrast = (
        masks[0].astype(np.int8)
        - masks[1].astype(np.int8)
        - masks[2].astype(np.int8)
        + masks[3].astype(np.int8)
    )
    interaction = float(contrast.mean())
    standard_error = (
        float(contrast.std(ddof=1) / np.sqrt(samples)) if samples > 1 else 0.0
    )
    margin = 1.96 * standard_error
    result: dict[str, float | int] = {
        "samples": samples,
        "interaction_ler": interaction,
        "standard_error": standard_error,
        "ci95_low": max(-2.0, interaction - margin),
        "ci95_high": min(2.0, interaction + margin),
    }
    result.update(
        {
            f"contrast_count_{value:+d}": int(np.count_nonzero(contrast == value))
            for value in range(-2, 3)
        }
    )
    return result


def paired_error_statistics(
    candidate_errors: np.ndarray,
    baseline_errors: np.ndarray,
) -> dict[str, float | int]:
    candidate = np.asarray(candidate_errors, dtype=np.bool_).reshape(-1)
    baseline = np.asarray(baseline_errors, dtype=np.bool_).reshape(-1)
    if candidate.shape != baseline.shape:
        raise ValueError(
            f"paired error masks must have the same shape: {candidate.shape} != {baseline.shape}"
        )
    samples = int(candidate.size)
    if samples == 0:
        raise ValueError("paired error masks must not be empty")

    candidate_only = int(np.count_nonzero(candidate & ~baseline))
    baseline_only = int(np.count_nonzero(~candidate & baseline))
    both = int(np.count_nonzero(candidate & baseline))
    neither = samples - candidate_only - baseline_only - both
    differences = candidate.astype(np.int8) - baseline.astype(np.int8)
    delta = float(differences.mean())
    standard_error = (
        float(differences.std(ddof=1) / np.sqrt(samples)) if samples > 1 else 0.0
    )
    margin = 1.96 * standard_error
    return {
        "samples": samples,
        "candidate_only_errors": candidate_only,
        "baseline_only_errors": baseline_only,
        "both_errors": both,
        "neither_errors": neither,
        "delta_ler": delta,
        "standard_error": standard_error,
        "ci95_low": max(-1.0, delta - margin),
        "ci95_high": min(1.0, delta + margin),
    }


def paired_error_comparison(
    method_a: str,
    errors_a: np.ndarray,
    method_b: str,
    errors_b: np.ndarray,
    *,
    basis: str,
) -> dict[str, Any]:
    """Summarize two shot-aligned logical-error masks."""
    stats = paired_error_statistics(errors_a, errors_b)
    return {
        "basis": basis,
        "method_a": method_a,
        "method_b": method_b,
        "samples": stats["samples"],
        "both_error": stats["both_errors"],
        "a_only_error": stats["candidate_only_errors"],
        "b_only_error": stats["baseline_only_errors"],
        "neither_error": stats["neither_errors"],
        "ler_delta_a_minus_b": stats["delta_ler"],
        "paired_standard_error": stats["standard_error"],
        "ler_delta_ci95_normal": [stats["ci95_low"], stats["ci95_high"]],
    }


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Compare PyMatching and replaceable predecoder models on identical samples."
    )
    config_group = parser.add_mutually_exclusive_group()
    config_group.add_argument(
        "--config-name", default="examples/qadapt/config_qadapt_t0_base"
    )
    config_group.add_argument(
        "--config-file", type=Path, help="Explicit YAML path, including generated OOD configs."
    )
    parser.add_argument("--distance", type=int, default=9)
    parser.add_argument("--n-rounds", type=int, default=9)
    parser.add_argument("--num-samples", type=int, default=262144)
    parser.add_argument("--latency-num-samples", type=int, default=10000)
    parser.add_argument("--batch-size", type=int, default=2048)
    parser.add_argument("--num-workers", type=int, default=0)
    parser.add_argument("--seed", type=int, default=12345)
    parser.add_argument("--device", default=None)
    parser.add_argument(
        "--basis",
        choices=("both", "X", "Z"),
        default="both",
        help="Measurement basis to evaluate.",
    )
    parser.add_argument(
        "--stim-samples-dir",
        default=None,
        help=(
            "Optional directory containing samples_X.dets/metadata_X.json and/or "
            "samples_Z.dets/metadata_Z.json. When omitted, Stim generates samples."
        ),
    )
    parser.add_argument(
        "--model",
        action="append",
        type=parse_model_spec,
        required=True,
        help=(
            "Repeatable model spec: name:model_id:/path/to/checkpoint "
            "(.pt or .safetensors)."
        ),
    )
    parser.add_argument(
        "--paired-comparison",
        action="append",
        type=parse_comparison_spec,
        default=[],
        help="Repeatable paired comparison: candidate:baseline.",
    )
    parser.add_argument(
        "--factorial-contrast",
        action="append",
        type=parse_factorial_contrast_spec,
        default=[],
        help="Repeatable contrast: name:cell_11:cell_10:cell_01:cell_00.",
    )
    parser.add_argument(
        "--output",
        default="outputs/paired_inference_compare/fast_vs_fastopt.json",
        help="JSON output path. A CSV summary is written next to it.",
    )
    parser.add_argument(
        "--residual-output-dir",
        default=None,
        help=(
            "Optional directory for full residual detector tensors. One uint8 "
            "PyTorch tensor is written per basis and model."
        ),
    )
    return parser.parse_args(argv)


def set_all_seeds(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def resolve_stim_samples_dir(args: argparse.Namespace) -> Path | None:
    value = getattr(args, "stim_samples_dir", None) or os.environ.get(
        "PREDECODER_STIM_SAMPLES_DIR"
    )
    if not value:
        return None
    path = Path(value).expanduser()
    return path if path.is_absolute() else REPO_ROOT / path


def build_cfg(args: argparse.Namespace, model: ModelSpec, basis: str) -> Any:
    explicit_path = getattr(args, "config_file", None)
    cfg_path = (
        Path(explicit_path).expanduser()
        if explicit_path is not None
        else config_path(args.config_name)
    )
    cfg = OmegaConf.load(cfg_path)
    cfg.model_id = model.model_id
    cfg.distance = args.distance
    cfg.n_rounds = args.n_rounds
    cfg.workflow.task = "inference"

    spec = validate_public_config(cfg)
    cfg = apply_public_defaults_and_model(cfg, spec)
    cfg.model_checkpoint_file = str(model.checkpoint)
    cfg.test.meas_basis_test = basis
    cfg.test.num_samples = int(args.num_samples)
    cfg.test.latency_num_samples = int(args.latency_num_samples)
    cfg.test.batch_size = int(args.batch_size)
    cfg.test.dataloader_num_workers = int(args.num_workers)
    stim_samples_dir = resolve_stim_samples_dir(args)
    if stim_samples_dir:
        cfg.test.stim_samples_dir = str(stim_samples_dir)
    return cfg


def make_dataset(cfg: Any, seed: int):
    py_state = random.getstate()
    np_state = np.random.get_state()
    torch_state = torch.get_rng_state()
    cuda_state = torch.cuda.get_rng_state_all() if torch.cuda.is_available() else None
    try:
        set_all_seeds(seed)
        return DatapipeFactory.create_datapipe_inference(cfg)
    finally:
        random.setstate(py_state)
        np.random.set_state(np_state)
        torch.set_rng_state(torch_state)
        if cuda_state is not None:
            torch.cuda.set_rng_state_all(cuda_state)


def time_single_shot(matcher: pymatching.Matching, syndromes: np.ndarray, n_rounds: int) -> float:
    n_rounds = max(int(n_rounds), 1)
    if syndromes.size == 0:
        return float("nan")
    if torch.cuda.is_available():
        torch.cuda.synchronize()
    warmup_n = min(50, len(syndromes))
    for i in range(warmup_n):
        matcher.decode(np.asarray(syndromes[i], dtype=np.uint8))

    times = []
    for row in syndromes:
        start = time.perf_counter()
        matcher.decode(np.asarray(row, dtype=np.uint8))
        times.append(time.perf_counter() - start)
    return float(np.mean(times) / n_rounds * 1e6)


def build_matcher(dataset) -> tuple[pymatching.Matching, int]:
    circuit = dataset.circ.stim_circuit
    det_model = circuit.detector_error_model(decompose_errors=True, approximate_disjoint_errors=True)
    return pymatching.Matching.from_detector_error_model(det_model), int(circuit.num_observables)


def evaluate_pymatching(
    matcher: pymatching.Matching,
    dets_and_obs: np.ndarray,
    num_obs: int,
    latency_samples: int,
    n_rounds: int,
) -> tuple[dict[str, float | int], np.ndarray]:
    dets = np.ascontiguousarray(dets_and_obs[:, :-num_obs], dtype=np.uint8)
    obs = np.ascontiguousarray(dets_and_obs[:, -num_obs:], dtype=np.uint8)
    pred = matcher.decode_batch(dets).reshape(obs.shape)
    error_mask = np.asarray(pred != obs, dtype=np.bool_).reshape(obs.shape[0], -1).any(axis=1)
    errors = int(error_mask.sum())
    total = int(obs.shape[0])
    latency_rows = dets[: min(latency_samples, len(dets))]
    input_density = SyndromeDensityAccumulator()
    input_density.update(dets)
    return {
        "logical_errors": errors,
        "samples": total,
        "ler": float(errors / total) if total else float("nan"),
        "latency_us_per_round": time_single_shot(matcher, latency_rows, n_rounds),
        **input_density.statistics("input"),
    }, error_mask


def evaluate_model(
    model: torch.nn.Module,
    cfg: Any,
    dataset,
    matcher: pymatching.Matching,
    num_obs: int,
    device: torch.device,
    latency_samples: int,
    n_rounds: int,
    residual_tensor_path: Path | None = None,
) -> tuple[dict[str, Any], np.ndarray]:
    maps = _build_stab_maps(int(cfg.distance), getattr(cfg, "rotation", "XV"))
    module = PreDecoderMemoryEvalModule(model, cfg, maps, device).to(device)
    module.eval()
    loader = DataLoader(
        dataset,
        batch_size=int(cfg.test.batch_size),
        shuffle=False,
        num_workers=int(cfg.test.dataloader_num_workers),
        pin_memory=(device.type == "cuda"),
    )

    logical_errors = 0
    total = 0
    residual_chunks: list[np.ndarray] = []
    saved_residual_chunks: list[np.ndarray] = []
    error_chunks: list[np.ndarray] = []
    residual_count = 0
    input_density = SyndromeDensityAccumulator()
    residual_density = SyndromeDensityAccumulator()

    with torch.no_grad():
        for batch in loader:
            batch = dict_to_device(batch, device)
            dets_and_obs = batch["dets_and_obs"]
            dets_only = dets_and_obs[:, :-num_obs]
            gt_obs = dets_and_obs[:, -num_obs:].to(torch.int64).cpu()

            output = module(dets_only)
            pre_l = output[:, 0].to(torch.int64).cpu()
            residual = output[:, 1:].to(torch.uint8).cpu().numpy()
            input_density.update(dets_only.to(torch.uint8).cpu().numpy())
            residual_density.update(residual)
            if residual_tensor_path is not None:
                saved_residual_chunks.append(
                    np.ascontiguousarray(residual, dtype=np.uint8)
                )
            pred_obs = torch.from_numpy(matcher.decode_batch(residual)).reshape(gt_obs.shape)
            final_l = (pre_l.reshape(gt_obs.shape) + pred_obs).remainder(2)

            error_mask = (final_l != gt_obs).reshape(gt_obs.shape[0], -1).any(dim=1)
            logical_errors += int(error_mask.sum().item())
            total += int(gt_obs.shape[0])
            error_chunks.append(error_mask.numpy())

            if residual_count < latency_samples:
                take = min(latency_samples - residual_count, residual.shape[0])
                residual_chunks.append(np.ascontiguousarray(residual[:take], dtype=np.uint8))
                residual_count += take

    residual_rows = (
        np.concatenate(residual_chunks, axis=0) if residual_chunks else np.empty((0, 0), dtype=np.uint8)
    )
    all_errors = np.concatenate(error_chunks) if error_chunks else np.empty(0, dtype=np.bool_)
    result: dict[str, Any] = {
        "logical_errors": logical_errors,
        "samples": total,
        "ler": float(logical_errors / total) if total else float("nan"),
        "latency_us_per_round": time_single_shot(matcher, residual_rows, n_rounds),
        **model_density_statistics(input_density, residual_density),
    }
    if residual_tensor_path is not None:
        residual_tensor_path.parent.mkdir(parents=True, exist_ok=True)
        saved_residual = (
            np.concatenate(saved_residual_chunks, axis=0)
            if saved_residual_chunks
            else np.empty((0, 0), dtype=np.uint8)
        )
        torch.save(torch.from_numpy(saved_residual), residual_tensor_path)
        result.update(
            residual_tensor_path=str(residual_tensor_path),
            residual_tensor_rows=int(saved_residual.shape[0]),
            residual_tensor_detectors=int(saved_residual.shape[1]),
            residual_tensor_dtype="torch.uint8",
        )
    return result, all_errors


def build_paired_comparison_rows(
    error_masks_by_basis: dict[str, dict[str, np.ndarray]],
    comparisons: list[ComparisonSpec],
) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    basis_order = [basis for basis in ("X", "Z") if basis in error_masks_by_basis]
    for comparison in comparisons:
        candidate_chunks = []
        baseline_chunks = []
        for basis in basis_order:
            masks = error_masks_by_basis[basis]
            missing = {
                method
                for method in (comparison.candidate, comparison.baseline)
                if method not in masks
            }
            if missing:
                raise KeyError(f"paired comparison methods missing for {basis}: {sorted(missing)}")
            candidate = masks[comparison.candidate]
            baseline = masks[comparison.baseline]
            rows.append(
                {
                    "basis": basis,
                    "candidate": comparison.candidate,
                    "baseline": comparison.baseline,
                    **paired_error_statistics(candidate, baseline),
                }
            )
            candidate_chunks.append(candidate)
            baseline_chunks.append(baseline)
        if len(basis_order) > 1:
            rows.append(
                {
                    "basis": "both",
                    "candidate": comparison.candidate,
                    "baseline": comparison.baseline,
                    **paired_error_statistics(
                        np.concatenate(candidate_chunks),
                        np.concatenate(baseline_chunks),
                    ),
                }
            )
    return rows


def build_factorial_contrast_rows(
    error_masks_by_basis: dict[str, dict[str, np.ndarray]],
    contrasts: list[FactorialContrastSpec],
) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    basis_order = [basis for basis in ("X", "Z") if basis in error_masks_by_basis]
    for contrast in contrasts:
        chunks = {field: [] for field in ("cell_11", "cell_10", "cell_01", "cell_00")}
        for basis in basis_order:
            masks = error_masks_by_basis[basis]
            methods = {
                field: getattr(contrast, field)
                for field in ("cell_11", "cell_10", "cell_01", "cell_00")
            }
            missing = set(methods.values()) - set(masks)
            if missing:
                raise KeyError(f"factorial contrast methods missing for {basis}: {sorted(missing)}")
            stats = factorial_contrast_statistics(*(masks[methods[field]] for field in chunks))
            rows.append(
                {
                    "basis": basis,
                    "name": contrast.name,
                    **methods,
                    **stats,
                }
            )
            for field, method in methods.items():
                chunks[field].append(masks[method])
        if len(basis_order) > 1:
            rows.append(
                {
                    "basis": "both",
                    "name": contrast.name,
                    "cell_11": contrast.cell_11,
                    "cell_10": contrast.cell_10,
                    "cell_01": contrast.cell_01,
                    "cell_00": contrast.cell_00,
                    **factorial_contrast_statistics(
                        *(np.concatenate(chunks[field]) for field in chunks)
                    ),
                }
            )
    return rows


def mean_metric(rows: list[dict[str, Any]], name: str) -> float:
    values = [float(row[name]) for row in rows if row.get(name) is not None]
    return float(np.mean(values)) if values else float("nan")


def main() -> None:
    args = parse_args()
    stim_samples_dir = resolve_stim_samples_dir(args)
    if stim_samples_dir is not None:
        # DatapipeFactory historically gives the environment variable priority.
        # Synchronize it so an explicit CLI path cannot be silently shadowed.
        os.environ["PREDECODER_STIM_SAMPLES_DIR"] = str(stim_samples_dir)
    output_path = Path(args.output)
    if not output_path.is_absolute():
        output_path = REPO_ROOT / output_path
    output_path.parent.mkdir(parents=True, exist_ok=True)
    residual_output_dir = (
        Path(args.residual_output_dir) if args.residual_output_dir else None
    )
    if residual_output_dir is not None and not residual_output_dir.is_absolute():
        residual_output_dir = REPO_ROOT / residual_output_dir

    for spec in args.model:
        if not spec.checkpoint.exists():
            raise FileNotFoundError(f"Checkpoint not found for {spec.name}: {spec.checkpoint}")
    available_methods = {"pymatching", *(spec.name for spec in args.model)}
    for comparison in args.paired_comparison:
        missing = {comparison.candidate, comparison.baseline} - available_methods
        if missing:
            raise ValueError(f"Unknown paired comparison methods: {sorted(missing)}")
    for contrast in args.factorial_contrast:
        missing = {
            contrast.cell_11,
            contrast.cell_10,
            contrast.cell_01,
            contrast.cell_00,
        } - available_methods
        if missing:
            raise ValueError(f"Unknown factorial contrast methods: {sorted(missing)}")

    device = torch.device(args.device or ("cuda:0" if torch.cuda.is_available() else "cpu"))
    dist = SimpleNamespace(rank=0, world_size=1, device=device)
    bases = ["X", "Z"] if args.basis == "both" else [args.basis]

    model_cfgs = {spec.name: build_cfg(args, spec, basis=bases[0]) for spec in args.model}
    models = {}
    for spec in args.model:
        print(f"[load] {spec.name}: model_id={spec.model_id}, checkpoint={spec.checkpoint}")
        model = load_model_checkpoint(
            model_cfgs[spec.name],
            checkpoint=spec.checkpoint,
            model_id=spec.model_id,
            distributed=dist,
        )
        model.eval()
        models[spec.name] = model

    rows: list[dict[str, Any]] = []
    error_masks_by_basis: dict[str, dict[str, np.ndarray]] = {}
    paired_comparisons: list[dict[str, Any]] = []
    sample_metadata: dict[str, Any] = {}
    for basis_index, basis in enumerate(bases):
        dataset_cfg = build_cfg(args, args.model[0], basis=basis)
        dataset_seed = int(args.seed) + basis_index
        print(f"[data] basis={basis}, seed={dataset_seed}, samples={args.num_samples}")
        dataset = make_dataset(dataset_cfg, dataset_seed)
        if hasattr(dataset, "metadata"):
            sample_metadata[basis] = dict(dataset.metadata)
        matcher, num_obs = build_matcher(dataset)
        dets_and_obs = np.asarray(dataset.dets_and_obs, dtype=np.uint8)

        baseline, baseline_errors = evaluate_pymatching(
            matcher,
            dets_and_obs,
            num_obs,
            int(args.latency_num_samples),
            int(args.n_rounds),
        )
        error_masks_by_basis[basis] = {"pymatching": baseline_errors}
        baseline_row = {
            "basis": basis,
            "method": "pymatching",
            "model_id": "",
            "checkpoint": "",
            **baseline,
            "speedup_vs_pymatching": 1.0,
        }
        rows.append(baseline_row)
        basis_errors = {"pymatching": baseline_errors}
        print(
            f"[result] {basis} pymatching ler={baseline['ler']:.6f}, "
            f"latency={baseline['latency_us_per_round']:.3f} us/round"
        )

        for spec in args.model:
            cfg = build_cfg(args, spec, basis=basis)
            residual_tensor_path = (
                residual_output_dir / f"{basis}_{spec.name}_residual_detectors.pt"
                if residual_output_dir is not None
                else None
            )
            result, model_errors = evaluate_model(
                models[spec.name],
                cfg,
                dataset,
                matcher,
                num_obs,
                device,
                int(args.latency_num_samples),
                int(args.n_rounds),
                residual_tensor_path,
            )
            error_masks_by_basis[basis][spec.name] = model_errors
            speedup = float(baseline["latency_us_per_round"]) / float(result["latency_us_per_round"])
            row = {
                "basis": basis,
                "method": spec.name,
                "model_id": spec.model_id,
                "checkpoint": str(spec.checkpoint),
                **result,
                "speedup_vs_pymatching": speedup,
            }
            rows.append(row)
            basis_errors[spec.name] = model_errors
            print(
                f"[result] {basis} {spec.name} ler={result['ler']:.6f}, "
                f"latency={result['latency_us_per_round']:.3f} us/round, speedup={speedup:.3f}x"
            )
        for method_a, method_b in combinations(basis_errors, 2):
            paired_comparisons.append(
                paired_error_comparison(
                    method_a,
                    basis_errors[method_a],
                    method_b,
                    basis_errors[method_b],
                    basis=basis,
                )
            )

    if args.paired_comparison:
        paired_comparisons = build_paired_comparison_rows(
            error_masks_by_basis,
            args.paired_comparison,
        )
    factorial_contrasts = build_factorial_contrast_rows(
        error_masks_by_basis,
        args.factorial_contrast,
    )
    methods = sorted({row["method"] for row in rows})
    summary = []
    for method in methods:
        method_rows = [row for row in rows if row["method"] == method]
        summary_row: dict[str, Any] = {
            "method": method,
            "ler_avg": mean_metric(method_rows, "ler"),
            "latency_us_per_round_avg": mean_metric(method_rows, "latency_us_per_round"),
            "speedup_vs_pymatching_avg": mean_metric(method_rows, "speedup_vs_pymatching"),
            **combine_density_statistics(method_rows, "input"),
        }
        if any(row.get("residual_syndrome_elements") for row in method_rows):
            residual_stats = combine_density_statistics(method_rows, "residual")
            summary_row.update(residual_stats)
            summary_row.update(
                density_reduction_statistics(
                    float(summary_row["input_syndrome_density"]),
                    float(residual_stats["residual_syndrome_density"]),
                )
            )
        summary.append(summary_row)

    payload = {
        "config_name": args.config_name,
        "distance": args.distance,
        "n_rounds": args.n_rounds,
        "num_samples": args.num_samples,
        "latency_num_samples": args.latency_num_samples,
        "seed": args.seed,
        "device": str(device),
        "sample_source": "stim_files" if stim_samples_dir else "generated",
        "stim_samples_dir": str(stim_samples_dir) if stim_samples_dir else None,
        "sample_metadata": sample_metadata,
        "rows": rows,
        "summary": summary,
        "paired_comparisons": paired_comparisons,
        "factorial_contrasts": factorial_contrasts,
    }
    output_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")

    csv_path = output_path.with_suffix(".csv")
    fieldnames = [
        "basis",
        "method",
        "model_id",
        "logical_errors",
        "samples",
        "ler",
        "latency_us_per_round",
        "speedup_vs_pymatching",
        "input_density_shots",
        "input_syndrome_ones",
        "input_syndrome_elements",
        "input_density_shot_sum",
        "input_density_shot_sum_squares",
        "input_syndrome_density",
        "input_density_standard_error",
        "input_density_ci95_low",
        "input_density_ci95_high",
        "residual_density_shots",
        "residual_syndrome_ones",
        "residual_syndrome_elements",
        "residual_density_shot_sum",
        "residual_density_shot_sum_squares",
        "residual_syndrome_density",
        "residual_density_standard_error",
        "residual_density_ci95_low",
        "residual_density_ci95_high",
        "density_delta",
        "density_reduction_fraction",
        "density_reduction_factor",
        "residual_tensor_path",
        "residual_tensor_rows",
        "residual_tensor_detectors",
        "residual_tensor_dtype",
        "checkpoint",
    ]
    with csv_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow({field: row.get(field, "") for field in fieldnames})

    print(f"[write] {output_path}")
    print(f"[write] {csv_path}")


if __name__ == "__main__":
    main()
